version: "3.1"

services:
  mongo:
    image: mongo
    container_name: learning_graphql_mongo
    hostname: learning_graphql_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - learning_graphql_mongo:/data/db
      - learning_graphql_mongo_configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: learning_graphql_mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  learning_graphql_mongo:
  learning_graphql_mongo_configdb:
